config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h2 class="navbar-brand" >Simple AirBnb</h2>
  <p><%= link_to "Add Flat", flats_path, class: "btn btn-primary" %></p>
  </div>
</nav>

app/views/flats/index.html.erb
<nav class="d-flex justify-content-between px-5 navbar navbar-expand-lg navbar-light bg-light">
  <h2 class="navbar-brand" >Simple AirBnb</h2>
  <p><%= link_to "Add Flat", flats_path, class: "btn btn-primary" %></p>
  </div>
</nav>


<h1 class="text-center my-5">All our flats (<%=@flats.count%>)</h1>

<div class="container">
  <div class="row">
  <% @flats.each do |flat| %>
    <div class="col border rounded m-3 shadow p-3 mb-5 bg-body">
      <div class="bg-light">
        <h4><%=flat.name %></h4>
        <h6><%= flat.address %></h6>
        <p><i class="fa-solid fa-people-group"></i>  <%= flat.number_of_guests %>    <i class="fa-solid fa-euro-sign"></i>    <%= flat.price_per_night %></p>
      </div>

      <div class="bg-white">
        <%= link_to "More information", flats_path %>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>